function config = defaultConstellationConfig()

config = struct( ...
    'startTime', datetime(2026, 4, 2, 0, 0, 0, 'TimeZone', 'UTC'), ...
    'durationHours', 24, ...
    'timeStepMinutes', 1, ...
    'altitudeKm', 1000, ...
    'inclinationDeg', 15, ...
    'numPlanes', 8, ...
    'numSatellites', 48, ...
    'walkerPhasing', 1, ...
    'geoLatDeg', 0, ...
    'geoLonDeg', 113, ...
    'elevationMaskDeg', 10, ...
    'gdopAvailabilityThreshold', 50, ...
    'includeGeoHostedPayload', true, ...
    'enablePlots', true, ...
    'writeLog', true, ...
    'verbose', true);

end
