function metrics = evaluateConstellationDesign(config)

config = mergeConfig(defaultConstellationConfig(), config);

planeCount = round(config.numPlanes);
satelliteCount = round(config.numSatellites);

if planeCount < 1 || planeCount > 12
    error('Number of planes must be between 1 and 12.');
end
if satelliteCount < 6 || satelliteCount > 48
    error('Number of satellites must be between 6 and 48.');
end
if mod(satelliteCount, planeCount) ~= 0
    error('Walker constellation requires total satellites to be divisible by plane count.');
end

tspan = config.startTime + minutes(0:config.timeStepMinutes:config.durationHours * 60);
RAAN = 2 * pi * (0:planeCount - 1) / planeCount;

[users, siteNames, gridInfo] = generateIndonesiaGridTargets();

if config.verbose
    fprintf('Using %d grid midpoint targets (%d x %d) for %g%c to %g%c and %g%c to %g%c.\n', ...
        size(users, 1), ...
        numel(gridInfo.lonMidDeg), ...
        numel(gridInfo.latMidDeg), ...
        abs(gridInfo.latEdgeNorthDeg), char(176), ...
        abs(gridInfo.latEdgeSouthDeg), char(176), ...
        gridInfo.lonEdgeWestDeg, char(176), ...
        gridInfo.lonEdgeEastDeg, char(176));
end

rLeo = orbitProp( ...
    config.altitudeKm * 1e3, ...
    deg2rad(config.inclinationDeg), ...
    RAAN, ...
    satelliteCount, ...
    tspan, ...
    config.walkerPhasing);

if config.includeGeoHostedPayload
    rAll = addGeoHostedPayload( ...
        rLeo, ...
        tspan, ...
        deg2rad(config.geoLatDeg), ...
        deg2rad(config.geoLonDeg));
else
    rAll = rLeo;
end

[availabilityByTarget, visibleSat, visibleCountAll, meanVisibleAll, maxVisiblePerTarget] = ...
    satAvailability(rAll, users, config.elevationMaskDeg);
[gdopAllVisible, meanGDOPAllVisible] = satGDOP(rAll, users, visibleSat);

availabilityMask = visibleCountAll >= 4 & gdopAllVisible <= config.gdopAvailabilityThreshold;
availabilityByTarget = mean(availabilityMask, 1).';

stdVisibleAll = std(visibleCountAll, 0, 1).';
stdGDOPAllVisible = nan(size(meanGDOPAllVisible));
for idx = 1:numel(siteNames)
    validGDOPAllVisible = gdopAllVisible(:, idx);
    validGDOPAllVisible = validGDOPAllVisible(~isnan(validGDOPAllVisible));
    if ~isempty(validGDOPAllVisible)
        stdGDOPAllVisible(idx) = std(validGDOPAllVisible);
    end
end

cost = satCost(rAll, 1);
globalMeanVisibleOverTime = mean(visibleCountAll, 2, 'omitnan');
globalMeanGDOPOverTime = mean(gdopAllVisible, 2, 'omitnan');
globalAvailabilityOverTime = mean(availabilityMask, 2, 'omitnan');
globalMeanAvailability = mean(availabilityByTarget, 'omitnan');
globalMeanVisible = mean(meanVisibleAll, 'omitnan');
globalMeanGDOPAllVisible = mean(meanGDOPAllVisible, 'omitnan');
globalMeanGDOPDeviation = mean(stdGDOPAllVisible, 'omitnan');

metrics = struct( ...
    'config', config, ...
    'tspan', tspan, ...
    'users', users, ...
    'siteNames', {siteNames}, ...
    'gridInfo', gridInfo, ...
    'rAll', rAll, ...
    'visibleSat', visibleSat, ...
    'visibleCountAll', visibleCountAll, ...
    'meanVisibleAll', meanVisibleAll, ...
    'maxVisiblePerTarget', maxVisiblePerTarget, ...
    'availabilityByTarget', availabilityByTarget, ...
    'gdopAllVisible', gdopAllVisible, ...
    'meanGDOPAllVisible', meanGDOPAllVisible, ...
    'stdVisibleAll', stdVisibleAll, ...
    'stdGDOPAllVisible', stdGDOPAllVisible, ...
    'availabilityMask', availabilityMask, ...
    'cost', cost, ...
    'globalMeanVisibleOverTime', globalMeanVisibleOverTime, ...
    'globalMeanGDOPOverTime', globalMeanGDOPOverTime, ...
    'globalAvailabilityOverTime', globalAvailabilityOverTime, ...
    'globalMeanAvailability', globalMeanAvailability, ...
    'globalMeanVisible', globalMeanVisible, ...
    'globalMeanGDOP', globalMeanGDOPAllVisible, ...
    'globalGDOPDeviation', globalMeanGDOPDeviation, ...
    'elevationMaskDeg', config.elevationMaskDeg, ...
    'gdopAvailabilityThreshold', config.gdopAvailabilityThreshold);

end
